services:
  unbgeology-mongodb-lib-unb-ca:
    image: ghcr.io/unb-libraries/unbgeology.mongodb.lib.unb.ca:8.x
    env_file:
      - ./env/mongo.env
    restart: unless-stopped
    container_name: unbgeology-mongodb-lib-unb-ca
    platform: linux/arm64/v8
    ports:
      - 27017:27017
    volumes:
      - unbgeology_mongodb_data:/data/db
      - unbgeology_mongodb_config:/data/configdb
    networks:
      - unbgeology.lib.unb.ca
  
  unbgeology-lib-unb-ca:
    build:
      context: .
    depends_on:
      - unbgeology-mongodb-lib-unb-ca
      - idp-saml-unbgeology-lib-unb-ca
    restart: unless-stopped
    container_name: unbgeology-lib-unb-ca
    volumes:
      - ./app:/app/html
      - ./files:/app/files
    env_file:
      - ./env/nuxt.env
    networks:
      - unbgeology.lib.unb.ca
    ports:
      - 3118:80
      - 31180:31180
      - 9118:9118

  idp-saml-unbgeology-lib-unb-ca:
    image: ghcr.io/unb-libraries/simplesamlphp:1.x
    container_name: idp-unbgeology-lib-unb-ca
    restart: unless-stopped
    env_file:
      - ./env/saml.env
    networks:
      - unbgeology.lib.unb.ca
    ports:
      - 6118:8080
      - 61180:8443

volumes:
  unbgeology_mongodb_data:
  unbgeology_mongodb_config:

networks:
  unbgeology.lib.unb.ca:
    name: unbgeology.lib.unb.ca
